// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>
using System;   
// TextTemplatingFileGenerator
// asdf
public class TestClass
{
   public static void HelloPot()
   {
      Console.WriteLine("Hello, POT");
   }
}
